name: ecommerce_app
description: "Deep into Bloc (cubit) - DI - Clean architucture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Routing
  go_router: ^14.2.7
  
  # State Management
  flutter_bloc: ^8.1.6
  
  # Dependency Injection
  get_it: ^7.7.0
  
  # Network
  dio: ^5.4.3+1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Utils
  equatable: ^2.0.5
  flutter_svg: ^2.2.1
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Functional Programming
  dartz: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  image: ^4.2.0
  
  # JSON Serialization
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/objects/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700



flutter_assets:
  assets_path: assets/
  output_path: lib/core/constents/
  filename: assets.dart